# Site settings
title: "Javi Mollà"
email: javimollamico@gmail.com
description: "My weird programming problems and (mostly) </br> good solutions to them"
baseurl: ""
url: "http://jmolla31.github.io"
title_description: "My weird programming problems and 

(mostly) good solutions to them"
title_image: "https://avatars3.githubusercontent.com/u/33100083"
google_analytics: 
disqus_account: 
github_repository: https://github.com/jmolla31/jmolla31.github.io
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  jmolla31
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: https://stackoverflow.com/users/10816810/javi-mollà-micó
xing_link:
facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
